import { isStringAnInteger } from "./utils";

type Signature = string;
type Key = string;
type Hash = string;

abstract class ThresholdCryptoScheme {
  /**
   * @param threshold The thereshold.
   * @param n The number of private keys.
   */
  constructor(
    public threshold: number,
    public n: number,
  ) {}

  /**
   * Generates some keys....
   *
   * @returns A public key and a list of n private keys.
   */
  abstract keygen(): [Key, Key[]];

  /**
   * Generates a new partial signature on a message from a private key.
   *
   * @param msg The message to sign.
   * @param private_key The private key to sign with.
   * @returns A partial signature.
   */
  abstract sign(msg: string, private_key: Key): Signature;

  /**
   * Produces a digital signatue on the message by combining k partial signatures.
   *
   * @param msg The message to sign.
   * @param partial_signatures An array of k partial signatures.
   * @returns A full signature that can be verified by `verify` on success. Otherwise null.
   */
  abstract combine(
    msg: string,
    partial_signatures: Signature[],
  ): Signature | null;

  /**
   * Verifies the message with the given full signature and public key.
   *
   * @param msg The message to verify.
   * @param signature The full signature to verify with (generated by `combine`).
   * @param public_key The public key.
   * @returns True if valid, otherwise false.
   */
  abstract verify(msg: string, signature: Signature, public_key: Key): boolean;
}

/**
 * A mock implementation of threshold cryptography.
 */
class MockCrypto extends ThresholdCryptoScheme {
  keygen(): [Key, Key[]] {
    const privateKeys = [];
    for (let i = 0; i < this.threshold; i++) {
      privateKeys.push("PrivateKey:" + i.toString());
    }

    return ["PublicKey", privateKeys];
  }

  sign(msg: string, private_key: Key): Signature {
    return "PartialSigned:" + private_key + ":" + msg;
  }

  combine(msg: string, partial_signatures: Signature[]): Signature | null {
    if (partial_signatures.length < this.threshold) {
      return null;
    }

    const intSignatures = new Set<number>(); // set to ensure no duplicates
    for (let signature of partial_signatures) {
      const sections = signature.split(":");
      if (sections.length === 4) {
        if (
          sections[0] === "PartialSigned" &&
          sections[1] === "PrivateKey" &&
          isStringAnInteger(sections[2])
        ) {
          intSignatures.add(parseInt(sections[2], 10));
        }
      } else {
        return null;
      }
    }

    if (intSignatures.size < this.threshold) {
      return null;
    }

    return "Signed:" + msg;
  }

  verify(msg: string, signature: Signature, public_key: Key): boolean {
    if (public_key !== "PublicKey") {
      return false;
    }

    return "Signed:" + msg === signature;
  }
}

/**
 * An implementation of Shamir Secret Sharing.
 */
class SSS extends ThresholdCryptoScheme {
  keygen(): [Key, Key[]] {
    return ["TODO", []];
  }

  sign(msg: string, private_key: Key): Signature {
    return "TODO";
  }

  combine(msg: string, partial_signatures: Signature[]): Signature | null {
    return "TODO";
  }

  verify(msg: string, signature: Signature, public_key: Key): boolean {
    return false; // TODO
  }
}

/**
 * A cryptographic hash function (a message digest).
 *
 * @param msg The message to hash.
 * @returns A fixed-length hash.
 */
function hash(msg: string): Hash {
  return "Hashed:" + msg; // TODO
}

function test() {
  const crypto = new MockCrypto(3, 5);
  const keys = crypto.keygen();
  console.log("Keys: ", keys);

  const msg = "Hello";
  const signatures = [];
  for (let key of keys[1]) {
    signatures.push(crypto.sign(msg, key));
  }

  console.log("Signatures: ", signatures);

  const full_sig1 = crypto.combine(msg, signatures);
  const full_sig2 = crypto.combine(msg, signatures.slice(0, 2));

  console.log("Full Signature Try 1 (should succeed): ", full_sig1);
  console.log("Full Signature Try 2 (should fail): ", full_sig2);

  const verify1 = crypto.verify(msg, full_sig1 ?? "", keys[0]);
  const verify2 = crypto.verify(msg, "Some invalid signature", keys[0]);

  console.log("Verify 1 (should be true): ", verify1);
  console.log("Verify 2 (should be false): ", verify2);
}

test();
