import type { Signature, Key } from "./crypto_types.js";

/**
 * An abstract interface for threshold crypto scheme implementations.
 */
export default abstract class ThresholdCryptoScheme {
  /**
   * @param threshold The thereshold.
   * @param n The number of private keys.
   */
  constructor(
    public threshold: number,
    public n: number,
  ) {}

  /**
   * Generates a public key and multiple private keys.
   *
   * @returns A public key and a list of n private keys.
   */
  abstract keygen(): [Key, Key[]];

  /**
   * Generates a new partial signature on a message from a private key.
   *
   * @param msg The message to sign.
   * @param private_key The private key to sign with.
   * @returns A partial signature.
   */
  abstract sign(msg: string, private_key: Key): Signature;

  /**
   * Produces a digital signatue on the message by combining k partial signatures.
   *
   * @param msg The message to sign.
   * @param partial_signatures An array of k partial signatures.
   * @returns A full signature that can be verified by `verify` on success. Otherwise null.
   */
  abstract combine(msg: string, partial_signatures: Signature[]): Signature | null;

  /**
   * Verifies the message with the given full signature and public key.
   *
   * @param msg The message to verify.
   * @param signature The full signature to verify with (generated by `combine`).
   * @param public_key The public key.
   * @returns True if valid, otherwise false.
   */
  abstract verify(msg: string, signature: Signature, public_key: Key): boolean;
}
